apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Demo 1
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
on:
  workflow_dispatch:
    inputs:
      achoice:
        type: choice
        options:
          - op1
          - op2
        default: ""
        description: only change description
