apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Example 4
on:
 workflow_dispatch:
   inputs:
     Select-env:
       type: choice
       options:
         - dev
         - staging
         - production
       default: dev
       required: true
       description: Select the environment for deployment.
jobs:
 build:
   steps:
     - name: Deploy to selected environment
       uses: docker://golang:1.20.3-alpine3.17
       shell: sh
       run: |
         echo "Deploying to ${inputs.Select-env} environment"
         # Add deployment steps based on the selected environment

