apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Example 2
on:
 workflow_dispatch:
   inputs:
     RetryCount:
       type: number
       default: 3
       required: true
       description: Retry deployment a certain number of times.
jobs:
 build:
   steps:
     - name: Retry deployment
       uses: docker://golang:1.20.3-alpine3.17
       shell: sh
       run: |
         for i in $(seq 1 ${{inputs.retry_count}}); do
           echo "Attempt $i"
         done
