apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      cadena1:
        type: string
        default: defaultval1
        required: true
        description: description 1
      numero1:
        type: number
        default: 666
        description: asdf
      bool1:
        type: boolean
        default: true
        required: true
        description: bool 1 desc
      options1:
        type: choice
        options:
          - num 1
          - num 2
          - num 3
        default: num 2
        required: true
        description: opst
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
