apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      s1:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        default: opt3
        required: true
        description: description 1adsfadsfaf
      s2:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        required: true
        description: description 1adsfasdf
      s3:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        required: false
        description: description 14444
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello ${{ inputs.s1}}"
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello ${{ inputs.s2}}"
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello ${{ inputs.s3}}"
