apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      cadena1:
        type: string
        default: defaultval1
        required: true
        description: description 1
      numero1:
        type: number
        default: 9.22337203699999999854776e+28
        required: true
        description: description 2
      bool1:
        type: boolean
        default: true
        required: true
        description: description 3
      options1:
        type: choice
        options:
          - num 1
          - num 3
        default: num 3
        required: true
        description: description 4
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
