apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflowab comit
jobs:
  my-job-1:
    steps:
      - name: My first step
        uses: docker://alpine:3.18
        id: print_params
        run: echo "${{ inputs.s1 }}"
         echo "${{ inputs.s2 }}"
on:
  workflow_dispatch:
    inputs:
      s1:
        type: string
        default: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
          veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
          ea commodo consequat. Duis aute irure dolor in reprehenderit in
          voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
          sint occaecat cupidatat non  proident, sunt in culpa qui officia
          deserunt mollit anim id est laborum.
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non  proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum.
      s2:
        type: string
        required: true
        description: short desc
