apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflowab
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  my-job-1:
    steps:
      - name: My first step 
        uses: docker://alpine:3.18
        id: step1
        run: echo "hello there" 
      