apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow new only a boolean
on:
  workflow_dispatch:
    inputs:
      a:
        type: boolean
        required: true
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
