apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflowab comit
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      a:
        type: choice
        options:
          - asdf
          - asdf
          - asdf
      b:
        type: number
      c:
        type: boolean
      e:
        type: string
      f:
        type: string
      g:
        type: string
      h:
        type: string
      i:
        type: string
      j:
        type: string
jobs:
  my-job-1:
    outputs:
      output1: ${{ steps.step1.outputs.greeting }}
      output2: ${{ steps.step2.outputs.greeting }}
    steps:
      - name: My first step
        uses: docker://alpine:3.18
        id: step1
        run: echo "hello there" > "$CLOUDBEES_OUTPUTS/greeting"
      - name: My second step
        uses: docker://alpine:3.18
        id: step2
        run: echo "from the hive" > "$CLOUDBEES_OUTPUTS/greeting"
