apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello ${{ inputs.nametoprint }}"
on:
  workflow_dispatch:
    inputs:
      nametoprint:
        type: string
        description: decription for the field
  push:
    branches:
      - main
