apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow 6666
on:
  workflow_dispatch:
    inputs:
      param1:
        type: string
        default: mlcbdefval
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
