apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflowab comit
jobs:
  my-job-1:
    outputs:
      output1: ${{ steps.step1.outputs.greeting }}
      output2: ${{ steps.step2.outputs.greeting }}
    steps:
      - name: My first step
        uses: docker://alpine:3.18
        id: step1
        run: echo "hello there" > "$CLOUDBEES_OUTPUTS/greeting"
      - name: My second step
        uses: docker://alpine:3.18
        id: step2
        run: echo "from the hive" > "$CLOUDBEES_OUTPUTS/greeting"
on:
  workflow_dispatch:
    inputs:
      s1:
        type: string
        default: l
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum.
